import { useCallback, useEffect, useRef, useState } from 'react'
import type { CSSProperties, ReactNode } from 'react'
import { Activity, ArrowLeft, Bike, BookOpen, ChevronRight, Clock3, Copy, Database, Dumbbell, Footprints, HeartPulse, LogOut, Moon, RefreshCw, Route, Save, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Target, Timer, X } from 'lucide-react'
import { workoutPlans } from './workouts'
import type { LiftPlan } from './workouts'
import './App.css'
import './ChartLabels.css'
import './ProfileMenu.css'
import './Lifting.css'

type N = number | null
type RangeKey = 'day' | 'week' | 'month'
type SessionUser = { email?: string; name?: string; picture?: string }
type Summary = { date:string; partialDay:boolean; caloriesConsumed:N; restingEnergy:N; activeEnergy:N; totalExpenditure:N; energyBalance:N; protein:N; carbs:N; fat:N; fiber:N; sleepHours:N; restingHeartRate:N; hrv:N; respiratoryRate:N; bloodOxygen:N; walkingHeartRateAverage:N; stepCount:N; distanceMiles:N; cyclingDistanceMiles:N; swimmingDistanceYards:N; swimmingStrokes:N; standMinutes:N; flightsClimbed:N; exerciseMinutes:N; vo2Max:N }
type FoodEntry = { time:string; meal:string; food:string; portion:string; calories:N; protein:N; carbs:N; fat:N; fiber:N }
type WorkoutEntry = { time:string; activity:string; durationMinutes:N; activeCalories:N; distanceMiles:N; averagePace:string; averageHeartRate:N; effort:string; location:string; swimmingDistanceYards:N; stepCount:N; strokeCount:N; dataQuality:string }
type TrendPoint = Summary & { workoutCount:number }
type GoalRange = { minimum:N; target:N; maximum:N }
type GoalKey = 'calories'|'protein'|'carbs'|'fat'|'fiber'|'move'|'exercise'|'stand'|'steps'|'sleepHours'
type GoalValues = Record<GoalKey,number>
type GoalProfile = { heightIn:number|null;weightLb:number|null;age:number|null;objective:'maintenance'|'deficit'|'gain' }
type DashboardData = { generatedAt:string; today:{summary:Summary;foodEntries:FoodEntry[];workouts:WorkoutEntry[];supplements:Array<{name:string;dose:string}>}; goals:Partial<Record<GoalKey,GoalRange>>; goalProfile?:GoalProfile; trends:TrendPoint[]; coverage:{days:number;workouts:number;foodEntries:number}; storage?:string }
type SyncToken = { token:string; tokenPrefix?:string; createdAt?:string; lastUsedAt?:string|null; endpoint:string; shortcutUrl:string; instructions:string }

type GoalApiResponse = GoalValues & { profile:GoalProfile; autoSet?:{objective:string;averageExpenditure:number;historyDays:number;usedFallback:boolean;note:string} }

const fmt=(v:N|undefined,d=0)=>v==null?'Not logged':new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(v)
const dateFmt=(s:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(`${s}T12:00:00`))
const longDate=(s:string)=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date(`${s}T12:00:00`))
const duration=(v:N|undefined)=>v==null?'Not logged':`${Math.floor(v)}h ${Math.round((v%1)*60)}m`
const positive=(v:N|undefined)=>v!=null&&v>0
const goalTarget=(goals:DashboardData['goals']|undefined,key:GoalKey,fallback:number)=>goals?.[key]?.target??fallback

function useInView<T extends HTMLElement>(){const ref=useRef<T|null>(null);const[visible,setVisible]=useState(false);useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.18,rootMargin:'0px 0px -6% 0px'});observer.observe(node);return()=>observer.disconnect()},[]);return{ref,visible}}

export default function App(){
  const[session,setSession]=useState<{loading:boolean;authenticated:boolean;user:SessionUser|null}>({loading:true,authenticated:false,user:null})
  const[data,setData]=useState<DashboardData|null>(null)
  const[loading,setLoading]=useState(false)
  const[error,setError]=useState('')
  const[range,setRange]=useState<RangeKey>('day')
  const[profileOpen,setProfileOpen]=useState(false)
  const[syncOpen,setSyncOpen]=useState(false)
  const[goalsOpen,setGoalsOpen]=useState(false)
  const[page,setPage]=useState<'dashboard'|'lifting'>('dashboard')
  const[selectedLift,setSelectedLift]=useState<LiftPlan|null>(null)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/mlog',{cache:'no-store',headers:{Accept:'application/json'}});if(r.status===401){setSession({loading:false,authenticated:false,user:null});setData(null);return}const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load Fuel');setData(p)}catch(e){setError(e instanceof Error?e.message:'Unable to load Fuel')}finally{setLoading(false)}},[])
  useEffect(()=>{fetch('/api/auth/session').then(r=>r.json()).then(p=>setSession({loading:false,authenticated:p.authenticated,user:p.user||null})).catch(()=>setSession({loading:false,authenticated:false,user:null}))},[])
  useEffect(()=>{if(!session.authenticated)return;void load();const id=setInterval(load,30000);const focus=()=>void load();addEventListener('focus',focus);return()=>{clearInterval(id);removeEventListener('focus',focus)}},[session.authenticated,load])
  const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setSession({loading:false,authenticated:false,user:null});setData(null)}
  if(session.loading)return <Centered title="Fuel" text="Loading your dashboard."/>
  if(!session.authenticated)return <SignIn/>
  if(page==='lifting')return <LiftingPage selected={selectedLift} onSelect={setSelectedLift} onBack={()=>selectedLift?setSelectedLift(null):setPage('dashboard')}/>
  const s=data?.today.summary
  const workoutDetail=s?.exerciseMinutes!=null?`${fmt(s.exerciseMinutes)} total exercise minutes`:`${data?.today.workouts.length||0} activity summaries`
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="profile-shell"><button className="profile-button" onClick={()=>setProfileOpen(v=>!v)} aria-label="Open profile menu" aria-expanded={profileOpen}>{session.user?.picture?<img src={session.user.picture} alt="" referrerPolicy="no-referrer"/>:<span>{(session.user?.name||session.user?.email||'U').slice(0,1).toUpperCase()}</span>}</button>{profileOpen&&<ProfileMenu user={session.user} onGoals={()=>{setProfileOpen(false);setGoalsOpen(true)}} onSync={()=>{setProfileOpen(false);setSyncOpen(true)}} onLogout={logout}/>}</div><div><h1>Fuel</h1><p>{longDate(s?.date||new Date().toISOString().slice(0,10))}</p></div></div><div className="user"><button className="lift-nav-button" onClick={()=>setPage('lifting')}><Dumbbell size={17}/><span>Lifting</span></button><button className="refresh-button" onClick={load} aria-label="Refresh dashboard"><RefreshCw size={17} className={loading?'spin':''}/></button></div></header>
    {error&&<div className="error">{error}</div>}
    <EnergyHero summary={s} trends={data?.trends||[]} range={range} setRange={setRange}/>
    <Section title="Nutrition" detail="Daily intake compared with targets"/>
    <section className="panel nutrition-panel"><GoalRing label="Calories" value={s?.caloriesConsumed} target={goalTarget(data?.goals,'calories',1950)} unit="kcal"/><GoalBar label="Protein" value={s?.protein} target={goalTarget(data?.goals,'protein',112)} unit="g"/><GoalBar label="Carbohydrates" value={s?.carbs} target={goalTarget(data?.goals,'carbs',300)} unit="g"/><GoalBar label="Fat" value={s?.fat} target={goalTarget(data?.goals,'fat',60)} unit="g"/><GoalBar label="Fiber" value={s?.fiber} target={goalTarget(data?.goals,'fiber',30)} unit="g"/></section>
    <Section title="Food consumed" detail={`${data?.today.foodEntries.length||0} entries today`}/><section className="panel"><EntryList empty="No food logged today.">{(data?.today.foodEntries||[]).map((e,i)=><FoodRow key={i} e={e}/>)}</EntryList></section>
    <Section title="Fitness" detail="Daily activity totals from Apple Health"/><ActivityRings summary={s} goals={data?.goals}/>
    <section className="metric-grid fitness-metrics"><Metric icon={<Activity/>} label="Active energy" value={s?.activeEnergy} unit="kcal"/><Metric icon={<Clock3/>} label="Exercise" value={s?.exerciseMinutes} unit="min"/><Metric icon={<Route/>} label="Walking + running" value={s?.distanceMiles} unit="mi" decimals={2}/><Metric icon={<Footprints/>} label="Steps" value={s?.stepCount} unit=""/>{positive(s?.standMinutes)&&<Metric icon={<Clock3/>} label="Stand time" value={s?.standMinutes} unit="min"/>}{positive(s?.flightsClimbed)&&<Metric icon={<Activity/>} label="Flights climbed" value={s?.flightsClimbed} unit="flights"/>}{positive(s?.cyclingDistanceMiles)&&<Metric icon={<Bike/>} label="Cycling distance" value={s?.cyclingDistanceMiles} unit="mi" decimals={2}/>}</section>
    <Section title="Workouts" detail={workoutDetail}/><section className="panel"><EntryList empty="No workout activity logged today.">{(data?.today.workouts||[]).map((e,i)=><WorkoutRow key={i} e={e}/>)}</EntryList></section>
    <Section title="Steps" detail={`Interactive 30-day movement trend · goal ${fmt(goalTarget(data?.goals,'steps',10000))}`}/><section className="panel chart-panel"><InteractiveLine data={data?.trends||[]} metric="stepCount" unit="steps" chartTitle="Daily steps" yLabel="Steps"/></section>
    <Section title="Vitals" detail="Resting cardiovascular, oxygen, and respiratory measures"/><section className="metric-grid"><Metric icon={<HeartPulse/>} label="Resting heart rate" value={s?.restingHeartRate} unit="bpm"/><Metric icon={<Activity/>} label="HRV" value={s?.hrv} unit="ms"/><Metric icon={<Activity/>} label="Respiratory rate" value={s?.respiratoryRate} unit="/min" decimals={1}/><Metric icon={<Activity/>} label="VO₂ max" value={s?.vo2Max} unit="mL/kg/min" decimals={1}/>{positive(s?.bloodOxygen)&&<Metric icon={<Activity/>} label="Blood oxygen" value={s?.bloodOxygen} unit="%" decimals={1}/>}{positive(s?.walkingHeartRateAverage)&&<Metric icon={<HeartPulse/>} label="Walking heart rate" value={s?.walkingHeartRateAverage} unit="bpm avg"/>}</section>
    <section className="panel chart-panel"><InteractiveLine data={data?.trends||[]} metric="restingHeartRate" unit="bpm" chartTitle="Resting heart rate trend" yLabel="Beats per minute"/></section>
    <Section title="Recovery" detail={`Sleep target ${fmt(goalTarget(data?.goals,'sleepHours',8),1)} hours`}/><section className="recovery-grid"><Metric icon={<Moon/>} label="Sleep" value={s?.sleepHours} unit="h" display={duration(s?.sleepHours)}/><section className="panel chart-panel"><InteractiveLine data={data?.trends||[]} metric="sleepHours" unit="h" decimals={1} chartTitle="Sleep duration" yLabel="Hours"/></section></section>
    <footer><Database size={15}/><span>{data?.coverage.days||0} days · {data?.coverage.workouts||0} active days · {data?.coverage.foodEntries||0} food entries · Neon Postgres</span></footer>
    {syncOpen&&<SyncSetup onClose={()=>setSyncOpen(false)}/>} 
    {goalsOpen&&<GoalsSetup initial={data} onClose={()=>setGoalsOpen(false)} onSaved={load}/>} 
  </main>
}

function LiftingPage({selected,onSelect,onBack}:{selected:LiftPlan|null;onSelect:(p:LiftPlan|null)=>void;onBack:()=>void}){
  useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'})},[selected])
  if(selected)return <main className="app-shell lifting-page"><header className="lifting-topbar"><div className="lifting-title"><button className="back-button" onClick={onBack} aria-label="Back to lifting plans"><ArrowLeft size={18}/></button><div><h1>Lifting</h1><p>View-only plan. Apple Health remains the activity log.</p></div></div></header><article className="lift-detail"><section className="panel lift-detail-hero"><span className={`level-pill level-${selected.level}`}>{selected.level}</span><h1>{selected.title}</h1><p>{selected.summary}</p><div className="lift-detail-meta"><span><Timer size={16}/>{selected.duration}</span><span><Target size={16}/>{selected.focus}</span></div><div className="lift-card-tags">{selected.tags.map(t=><span className="lift-tag" key={t}>{t}</span>)}</div></section><section className="panel lift-steps">{selected.steps.map((step,i)=><div className="lift-step" key={`${step.exercise}-${i}`}><div className="lift-phase">{step.phase}</div><div><h3>{step.exercise}</h3><p>{step.prescription}</p>{step.rest&&<p className="rest">Rest: {step.rest}</p>}{step.cues&&<p className="cues">{step.cues}</p>}</div></div>)}</section><section className="panel lifting-note">Choose loads that preserve the listed repetitions in reserve (RIR). Technical failure means the next repetition would require altered range, posture, or assistance. Do not force painful ranges, and use a spotter or safety arms for heavy presses and squats.</section></article></main>
  return <main className="app-shell lifting-page"><header className="lifting-topbar"><div className="lifting-title"><button className="back-button" onClick={onBack} aria-label="Back to dashboard"><ArrowLeft size={18}/></button><div><h1>Lifting</h1><p>Evidence-informed, view-only sessions</p></div></div></header><section className="panel lifting-intro"><h2>Choose a 30-45 minute session.</h2><p>These plans prioritize high-quality compound work, controlled weekly fatigue, and time-efficient supersets. Most working sets stop one to three repetitions before technical failure. Drop sets and cluster sets are used selectively rather than as defaults, and the recovery sessions stay deliberately easy.</p><div className="lifting-principles"><span>Dynamic warm-up first</span><span>1-3 reps in reserve</span><span>Compound lifts prioritized</span><span>Static stretching last</span><span>No logging from this page</span></div></section><div className="lift-grid">{workoutPlans.map(plan=><button className="lift-card" key={plan.id} onClick={()=>onSelect(plan)}><div className="lift-card-head"><h3>{plan.title}</h3><ChevronRight className="chevron" size={18}/></div><p className="lift-focus">{plan.focus}</p><p className="lift-summary">{plan.summary}</p><div className="lift-card-meta"><span><Timer size={14}/>{plan.duration}</span><span className={`level-pill level-${plan.level}`}>{plan.level}</span></div><div className="lift-card-tags">{plan.tags.map(t=><span className="lift-tag" key={t}>{t}</span>)}</div></button>)}</div><section className="panel lifting-research"><h3><BookOpen size={17}/> Programming basis</h3><p>The library uses progressive resistance training principles, adequate rest for strength work, moderate proximity to failure, full-range compound movements, and non-competing supersets when time is limited. Dynamic movements prepare the session, while short static holds are reserved for the end. Because running and swimming already create substantial endurance load, lower-body volume and failure work are constrained to protect recovery.</p></section></main>
}

function ProfileMenu({user,onGoals,onSync,onLogout}:{user:SessionUser|null;onGoals:()=>void;onSync:()=>void;onLogout:()=>void}){return <div className="profile-menu panel" role="menu"><div className="profile-menu-user"><strong>{user?.name||'Signed in'}</strong><span>{user?.email}</span></div><button onClick={onGoals} role="menuitem"><SlidersHorizontal size={17}/><span>Goals</span></button><button onClick={onSync} role="menuitem"><Settings size={17}/><span>Sync setup</span></button><button className="logout-menu-button" onClick={onLogout} role="menuitem"><LogOut size={17}/><span>Log out</span></button></div>}

function GoalsSetup({initial,onClose,onSaved}:{initial:DashboardData|null;onClose:()=>void;onSaved:()=>Promise<void>|void}){
  const defaults:GoalValues={calories:goalTarget(initial?.goals,'calories',1950),protein:goalTarget(initial?.goals,'protein',112),carbs:goalTarget(initial?.goals,'carbs',300),fat:goalTarget(initial?.goals,'fat',60),fiber:goalTarget(initial?.goals,'fiber',30),move:goalTarget(initial?.goals,'move',1000),exercise:goalTarget(initial?.goals,'exercise',80),stand:goalTarget(initial?.goals,'stand',120),steps:goalTarget(initial?.goals,'steps',10000),sleepHours:goalTarget(initial?.goals,'sleepHours',8)}
  const[goals,setGoals]=useState<GoalValues>(defaults)
  const[profile,setProfile]=useState<GoalProfile>(initial?.goalProfile||{heightIn:null,weightLb:null,age:null,objective:'maintenance'})
  const[busy,setBusy]=useState(false)
  const[message,setMessage]=useState('')
  const[autoNote,setAutoNote]=useState('')
  useEffect(()=>{fetch('/api/goals',{cache:'no-store'}).then(r=>r.json()).then((p:GoalApiResponse)=>{if(p.calories){setGoals({calories:p.calories,protein:p.protein,carbs:p.carbs,fat:p.fat,fiber:p.fiber,move:p.move,exercise:p.exercise,stand:p.stand,steps:p.steps,sleepHours:p.sleepHours});setProfile(p.profile)}}).catch(()=>{})},[])
  const submit=async(method:'PUT'|'POST')=>{setBusy(true);setMessage('');try{const body=method==='PUT'?{goals,profile}:profile;const r=await fetch('/api/goals',{method,headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(body)}),p:GoalApiResponse&{error?:string}=await r.json();if(!r.ok)throw new Error(p.error||'Unable to update goals.');setGoals({calories:p.calories,protein:p.protein,carbs:p.carbs,fat:p.fat,fiber:p.fiber,move:p.move,exercise:p.exercise,stand:p.stand,steps:p.steps,sleepHours:p.sleepHours});setProfile(p.profile);setAutoNote(p.autoSet?.note||'');setMessage(method==='POST'?'Goals calculated and saved.':'Goals saved.');await onSaved()}catch(e){setMessage(e instanceof Error?e.message:'Unable to update goals.')}finally{setBusy(false)}}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="goals-modal panel" role="dialog" aria-modal="true"><div className="sync-modal-head"><div><h2>Goals</h2><p>Set daily nutrition, activity, and recovery targets.</p></div><button className="icon-button" onClick={onClose}><X size={20}/></button></div><div className="goal-config-grid">{([
    ['calories','Calories','kcal'],['protein','Protein','g'],['carbs','Carbohydrates','g'],['fat','Fat','g'],['fiber','Fiber','g'],['move','Move','kcal'],['exercise','Exercise','min'],['stand','Stand','min'],['steps','Steps','steps'],['sleepHours','Sleep','hours']
  ] as Array<[GoalKey,string,string]>).map(([key,label,unit])=><label className="goal-field" key={key}><span>{label}<small>{unit}</small></span><input type="number" min="0" step={key==='sleepHours'?.1:1} value={goals[key]} onChange={e=>setGoals(g=>({...g,[key]:Number(e.target.value)}))}/></label>)}</div><button className="save-goals-button" disabled={busy} onClick={()=>void submit('PUT')}><Save size={17}/>Save goals</button><div className="auto-goals"><div className="auto-goals-head"><Sparkles size={18}/><div><h3>Automatically set goals</h3><p>Uses completed Apple Health expenditure days and excludes today.</p></div></div><div className="auto-profile-grid"><label>Height (in)<input type="number" value={profile.heightIn??''} onChange={e=>setProfile(p=>({...p,heightIn:e.target.value?Number(e.target.value):null}))}/></label><label>Weight (lb)<input type="number" value={profile.weightLb??''} onChange={e=>setProfile(p=>({...p,weightLb:e.target.value?Number(e.target.value):null}))}/></label><label>Age<input type="number" value={profile.age??''} onChange={e=>setProfile(p=>({...p,age:e.target.value?Number(e.target.value):null}))}/></label><label>Goal<select value={profile.objective} onChange={e=>setProfile(p=>({...p,objective:e.target.value as GoalProfile['objective']}))}><option value="maintenance">Maintenance</option><option value="deficit">Calorie deficit</option><option value="gain">Gain muscle</option></select></label></div><button className="auto-goals-button" disabled={busy} onClick={()=>void submit('POST')}><Sparkles size={17}/>Calculate and apply</button>{autoNote&&<p className="auto-note">{autoNote}</p>}</div>{message&&<p className="sync-message">{message}</p>}<p className="sync-note">Automatic targets are starting estimates. Adjust them based on weight trend, training performance, hunger, recovery, and medical guidance.</p></section></div>
}

function SyncSetup({onClose}:{onClose:()=>void}){const[record,setRecord]=useState<SyncToken|null>(null),[busy,setBusy]=useState(true),[message,setMessage]=useState('');const fetchToken=useCallback(async(method:'GET'|'POST'='GET')=>{setBusy(true);setMessage('');try{const r=await fetch('/api/health/token',{method,headers:{Accept:'application/json'}}),p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to provide a health sync token.');setRecord(p)}catch(e){setMessage(e instanceof Error?e.message:'Unable to provide a health sync token.')}finally{setBusy(false)}},[]);useEffect(()=>{void fetchToken()},[fetchToken]);const copy=async()=>{if(!record?.token)return;await navigator.clipboard.writeText(record.token);setMessage('Token copied.')};return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="sync-modal panel" role="dialog" aria-modal="true"><div className="sync-modal-head"><div><h2>Apple Health sync</h2><p>Neon-backed private storage</p></div><button className="icon-button" onClick={onClose}><X size={20}/></button></div><ol><li><a href={record?.shortcutUrl||'https://www.icloud.com/shortcuts/bfdc6b641b3f4172a7b842fc60dc1dd3'} target="_blank" rel="noreferrer">Install the Fuel Health Shortcut</a>.</li><li>Replace only the bearer token in the Shortcut with the token below.</li><li>Leave the endpoint and the word <strong>Bearer</strong> unchanged.</li></ol><label>Your bearer token</label><div className="token-box">{busy?'Loading token…':record?.token||'Token unavailable'}</div><button className="primary-sync-button" onClick={copy} disabled={!record?.token||busy}><Copy size={17}/>Copy token</button><div className="sync-actions"><a className="shortcut-button" href={record?.shortcutUrl||'https://www.icloud.com/shortcuts/bfdc6b641b3f4172a7b842fc60dc1dd3'} target="_blank" rel="noreferrer">Get Shortcut</a><button className="resync-button" onClick={()=>void fetchToken('POST')} disabled={busy}><RefreshCw size={16}/>Re-sync token</button></div>{message&&<p className="sync-message">{message}</p>}<p className="sync-note">Re-syncing immediately revokes the previous token. Imports update one record per date and do not create duplicate daily entries.</p></section></div>}

function ActivityRings({summary,goals}:{summary:Summary|undefined;goals:DashboardData['goals']|undefined}){const rings=[{label:'Move',value:summary?.activeEnergy||0,target:goalTarget(goals,'move',1000),unit:'CAL',radius:96,width:26,className:'move-ring'},{label:'Exercise',value:summary?.exerciseMinutes||0,target:goalTarget(goals,'exercise',80),unit:'MIN',radius:67,width:24,className:'exercise-ring'},{label:'Stand',value:summary?.standMinutes||0,target:goalTarget(goals,'stand',120),unit:'MIN',radius:40,width:22,className:'stand-ring'}],{ref,visible}=useInView<HTMLDivElement>();return <section ref={ref} className={`activity-rings panel ${visible?'is-visible':''}`}><div className="rings-graphic" role="img"><svg viewBox="0 0 240 240" aria-hidden="true">{rings.map(r=>{const c=2*Math.PI*r.radius,pct=Math.min(1,Math.max(0,r.value/r.target));return <g key={r.label} className={r.className}><circle className="fitness-track" cx="120" cy="120" r={r.radius} strokeWidth={r.width}/><circle className="fitness-progress" cx="120" cy="120" r={r.radius} strokeWidth={r.width} strokeDasharray={c} strokeDashoffset={c*(1-pct)}/></g>})}</svg></div><div className="rings-copy">{rings.map(r=><div className={`ring-stat ${r.className}`} key={r.label}><span>{r.label}</span><strong>{fmt(r.value)}/{fmt(r.target)}<small>{r.unit}</small></strong></div>)}</div></section>}
function EnergyHero({summary,trends,range,setRange}:{summary:Summary|undefined;trends:TrendPoint[];range:RangeKey;setRange:(r:RangeKey)=>void}){const days=range==='day'?1:range==='week'?7:30,visible=trends.slice(-days),consumed=visible.reduce((a,p)=>a+(p.caloriesConsumed||0),0),expended=visible.reduce((a,p)=>a+(p.totalExpenditure||0),0),balance=consumed&&expended?consumed-expended:null;return <section className="hero panel"><div className="hero-head"><div><span className="eyebrow">ENERGY BALANCE</span><h2>{balance==null?'Incomplete data':balance>0?`${fmt(balance)} kcal surplus`:`${fmt(Math.abs(balance))} kcal deficit`}</h2><p>{range==='day'?'Today':range==='week'?'Last 7 days':'Last 30 days'} · intake versus total expenditure</p></div><div className="tabs">{(['day','week','month'] as RangeKey[]).map(r=><button className={range===r?'active':''} onClick={()=>setRange(r)} key={r}>{r==='day'?'Day':r==='week'?'Week':'Month'}</button>)}</div></div><EnergyInteractiveChart data={visible}/><div className="hero-stats"><Stat label="Consumed" value={consumed||summary?.caloriesConsumed}/><Stat label="Resting" value={range==='day'?summary?.restingEnergy:visible.reduce((a,p)=>a+(p.restingEnergy||0),0)}/><Stat label="Active" value={range==='day'?summary?.activeEnergy:visible.reduce((a,p)=>a+(p.activeEnergy||0),0)}/><Stat label="Expended" value={expended||summary?.totalExpenditure}/></div></section>}
function EnergyInteractiveChart({data}:{data:TrendPoint[]}){const[active,setActive]=useState<number|null>(null),max=Math.max(1,...data.flatMap(p=>[p.caloriesConsumed||0,p.totalExpenditure||0]));if(!data.length)return <div className="empty">No energy data</div>;const p=active==null?null:data[active];return <div className="energy-viz animated-chart is-visible" onMouseLeave={()=>setActive(null)}><div className="chart-header-row"><div><strong className="chart-title">Daily energy intake and expenditure</strong><span className="chart-axis-note">Horizontal axis: date · Vertical axis: kilocalories</span></div><ChartLegend items={[["legend-consumed","Calories consumed"],["legend-expended","Total calories expended"]]}/></div><div className="bars">{data.map((d,i)=><button key={d.date} className={`bar-day ${i===active?'selected':''}`} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onBlur={()=>setActive(null)} onClick={()=>setActive(i)}><span className="bar consumed" style={{'--bar-height':`${Math.max(3,(d.caloriesConsumed||0)/max*100)}%`} as CSSProperties}/><span className="bar burned" style={{'--bar-height':`${Math.max(3,(d.totalExpenditure||0)/max*100)}%`} as CSSProperties}/>{i===active&&p&&<span className="point-label energy-point-label"><strong>{dateFmt(p.date)}</strong><span>{fmt(p.caloriesConsumed)} in</span><span>{fmt(p.totalExpenditure)} out</span></span>}<small>{dateFmt(d.date)}</small></button>)}</div><div className="x-axis-label">Date</div></div>}
function InteractiveLine({data,metric,unit,decimals=0,chartTitle,yLabel}:{data:TrendPoint[];metric:keyof TrendPoint;unit:string;decimals?:number;chartTitle:string;yLabel:string}){const points=data.map((p,i)=>({date:p.date,value:typeof p[metric]==='number'?p[metric] as number:null,i})).filter((p):p is{date:string;value:number;i:number}=>p.value!=null),[active,setActive]=useState<number|null>(null);if(points.length<2)return <div className="empty">Insufficient data</div>;const max=Math.max(...points.map(p=>p.value)),min=Math.min(...points.map(p=>p.value)),w=760,h=220,padX=42,padY=30,range=max-min||1,xy=points.map((p,i)=>({...p,x:padX+i/(points.length-1)*(w-padX*2),y:padY+(max-p.value)/range*(h-padY*2)})),a=active==null?null:xy[active],first=xy[0],last=xy.at(-1)!,labelLeft=a?`${Math.min(86,Math.max(12,(a.x/w)*100))}%`:'50%',labelTop=a?`${Math.min(80,Math.max(8,(a.y/h)*100))}%`:'50%';return <div className="interactive-line animated-chart is-visible" onMouseLeave={()=>setActive(null)}><div className="chart-header-row"><div><strong className="chart-title">{chartTitle}</strong><span className="chart-axis-note">Horizontal axis: date · Vertical axis: {yLabel}</span></div><ChartLegend items={[["legend-line",chartTitle]]}/></div><div className="chart-stage"><span className="y-axis-label">{yLabel}</span><svg viewBox={`0 0 ${w} ${h}`} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect(),idx=Math.round(((e.clientX-r.left)/r.width)*(points.length-1));setActive(Math.max(0,Math.min(points.length-1,idx)))}}><defs><linearGradient id={`fill-${String(metric)}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopOpacity=".18"/><stop offset="1" stopOpacity="0"/></linearGradient></defs><line className="gridline" x1={padX} x2={w-padX} y1={padY} y2={padY}/><line className="gridline" x1={padX} x2={w-padX} y1={h-padY} y2={h-padY}/><path className="area" d={`M ${xy[0].x} ${h-padY} L ${xy.map(p=>`${p.x} ${p.y}`).join(' L ')} L ${xy.at(-1)!.x} ${h-padY} Z`} fill={`url(#fill-${String(metric)})`}/><polyline className="trend-line" points={xy.map(p=>`${p.x},${p.y}`).join(' ')} fill="none"/>{a&&<line className="cursor" x1={a.x} x2={a.x} y1={padY} y2={h-padY}/>} {xy.map((p,i)=><circle key={p.date} cx={p.x} cy={p.y} r={i===active?6:3} onClick={()=>setActive(i)} onFocus={()=>setActive(i)} tabIndex={0}/>)}</svg>{a&&<div className="point-label line-point-label" style={{left:labelLeft,top:labelTop}}><strong>{dateFmt(a.date)}</strong><span>{fmt(a.value,decimals)} {unit}</span></div>}<span className="y-max-label">{fmt(max,decimals)} {unit}</span><span className="y-min-label">{fmt(min,decimals)} {unit}</span></div><div className="line-axis-footer"><span>{dateFmt(first.date)}</span><strong>Date</strong><span>{dateFmt(last.date)}</span></div></div>}
function ChartLegend({items}:{items:Array<[string,string]>}){return <div className="chart-legend">{items.map(([className,label])=><span key={label}><i className={className}/>{label}</span>)}</div>}
function GoalRing({label,value,target,unit}:{label:string;value:N|undefined;target:number;unit:string}){const pct=Math.min(100,Math.max(0,((value||0)/target)*100)),{ref,visible}=useInView<HTMLDivElement>();return <div ref={ref} className={`goal-ring ${visible?'is-visible':''}`}><div className="ring" style={{'--pct':`${pct*3.6}deg`} as CSSProperties}><div><strong>{fmt(value)}</strong><span>of {fmt(target)} {unit}</span></div></div><h3>{label}</h3></div>}
function GoalBar({label,value,target,unit}:{label:string;value:N|undefined;target:number;unit:string}){const pct=Math.min(120,Math.max(0,((value||0)/target)*100)),{ref,visible}=useInView<HTMLDivElement>();return <div ref={ref} className={`goal-bar ${visible?'is-visible':''}`}><div><strong>{label}</strong><span>{fmt(value)} / {fmt(target)} {unit}</span></div><div className="track"><i style={{'--goal-width':`${Math.min(100,pct)}%`} as CSSProperties}/></div></div>}
function Metric({icon,label,value,unit,decimals=0,display}:{icon:ReactNode;label:string;value:N|undefined;unit:string;decimals?:number;display?:string}){return <section className="metric-card panel"><span>{icon}</span><div><p>{label}</p><strong>{display||fmt(value,decimals)}</strong>{value!=null&&!display&&<small>{unit}</small>}</div></section>}
function Stat({label,value}:{label:string;value:N|undefined}){return <div><span>{label}</span><strong>{fmt(value)} kcal</strong></div>}
function Section({title,detail}:{title:string;detail:string}){return <div className="section-title"><h2>{title}</h2><p>{detail}</p></div>}
function EntryList({children,empty}:{children:ReactNode;empty:string}){const a=Array.isArray(children)?children:[children];return a.length?<div className="entry-list">{children}</div>:<div className="empty">{empty}</div>}
function FoodRow({e}:{e:FoodEntry}){return <article className="entry"><div><strong>{e.food||e.meal}</strong><span>{[e.time,e.meal,e.portion].filter(Boolean).join(' · ')}</span></div><div><strong>{fmt(e.calories)} kcal</strong><span>{fmt(e.protein,1)}g protein · {fmt(e.carbs,1)}g carbs · {fmt(e.fat,1)}g fat</span></div></article>}
function WorkoutRow({e}:{e:WorkoutEntry}){const facts=[e.swimmingDistanceYards!=null?`${fmt(e.swimmingDistanceYards)} yd`:e.distanceMiles!=null?`${fmt(e.distanceMiles,2)} mi`:'',e.strokeCount!=null?`${fmt(e.strokeCount)} strokes`:'',e.stepCount!=null?`${fmt(e.stepCount)} steps`:''].filter(Boolean);return <article className="entry"><div><strong>{e.activity||'Activity'}</strong><span>{facts.join(' · ')||e.dataQuality}</span></div><div><span>{e.dataQuality}</span></div></article>}
function Centered({title,text}:{title:string;text:string}){return <main className="center"><RefreshCw className="spin"/><h1>{title}</h1><p>{text}</p></main>}
function SignIn(){return <main className="center"><div className="signin"><h1>Fuel</h1><p>Your private nutrition, activity, and recovery dashboard.</p><button onClick={()=>location.assign('/api/auth/google/start')}><ShieldCheck size={18}/>Sign in with Google</button></div></main>}
