import { useCallback, useEffect, useRef, useState } from 'react'
import type { CSSProperties, ReactNode } from 'react'
import { Activity, Bike, Clock3, Copy, Database, Footprints, HeartPulse, LogOut, Moon, RefreshCw, Route, Settings, ShieldCheck, X } from 'lucide-react'
import './App.css'
import './ChartLabels.css'
import './ProfileMenu.css'

type N = number | null
type RangeKey = 'day' | 'week' | 'month'
type SessionUser = { email?: string; name?: string; picture?: string }
type Summary = { date:string; partialDay:boolean; caloriesConsumed:N; restingEnergy:N; activeEnergy:N; totalExpenditure:N; energyBalance:N; protein:N; carbs:N; fat:N; fiber:N; sleepHours:N; restingHeartRate:N; hrv:N; respiratoryRate:N; bloodOxygen:N; walkingHeartRateAverage:N; stepCount:N; distanceMiles:N; cyclingDistanceMiles:N; swimmingDistanceYards:N; swimmingStrokes:N; standMinutes:N; flightsClimbed:N; exerciseMinutes:N; vo2Max:N }
type FoodEntry = { time:string; meal:string; food:string; portion:string; calories:N; protein:N; carbs:N; fat:N; fiber:N }
type WorkoutEntry = { time:string; activity:string; durationMinutes:N; activeCalories:N; distanceMiles:N; averagePace:string; averageHeartRate:N; effort:string; location:string; swimmingDistanceYards:N; stepCount:N; strokeCount:N; dataQuality:string }
type TrendPoint = Summary & { workoutCount:number }
type GoalRange = { minimum:N; target:N; maximum:N }
type DashboardData = { generatedAt:string; today:{summary:Summary;foodEntries:FoodEntry[];workouts:WorkoutEntry[];supplements:Array<{name:string;dose:string}>}; goals:Partial<Record<'calories'|'protein'|'carbs'|'fat'|'fiber'|'sleepHours',GoalRange>>; trends:TrendPoint[]; coverage:{days:number;workouts:number;foodEntries:number}; storage?:string }
type SyncToken = { token:string; tokenPrefix?:string; createdAt?:string; lastUsedAt?:string|null; endpoint:string; shortcutUrl:string; instructions:string }

const fmt = (v:N|undefined, d=0) => v == null ? 'Not logged' : new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(v)
const dateFmt = (s:string) => new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(`${s}T12:00:00`))
const longDate = (s:string) => new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date(`${s}T12:00:00`))
const duration = (v:N|undefined) => v == null ? 'Not logged' : `${Math.floor(v)}h ${Math.round((v%1)*60)}m`
const positive = (v:N|undefined) => v != null && v > 0

function useInView<T extends HTMLElement>(){
  const ref=useRef<T|null>(null)
  const [visible,setVisible]=useState(false)
  useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.18,rootMargin:'0px 0px -6% 0px'});observer.observe(node);return()=>observer.disconnect()},[])
  return {ref,visible}
}

export default function App(){
  const [session,setSession]=useState<{loading:boolean;authenticated:boolean;user:SessionUser|null}>({loading:true,authenticated:false,user:null})
  const [data,setData]=useState<DashboardData|null>(null)
  const [loading,setLoading]=useState(false)
  const [error,setError]=useState('')
  const [range,setRange]=useState<RangeKey>('day')
  const [profileOpen,setProfileOpen]=useState(false)
  const [syncOpen,setSyncOpen]=useState(false)

  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/mlog',{cache:'no-store',headers:{Accept:'application/json'}});if(r.status===401){setSession({loading:false,authenticated:false,user:null});setData(null);return}const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load Fuel');setData(p)}catch(e){setError(e instanceof Error?e.message:'Unable to load Fuel')}finally{setLoading(false)}},[])
  useEffect(()=>{fetch('/api/auth/session').then(r=>r.json()).then(p=>setSession({loading:false,authenticated:p.authenticated,user:p.user||null})).catch(()=>setSession({loading:false,authenticated:false,user:null}))},[])
  useEffect(()=>{if(!session.authenticated)return;void load();const id=setInterval(load,30000);const focus=()=>void load();addEventListener('focus',focus);return()=>{clearInterval(id);removeEventListener('focus',focus)}},[session.authenticated,load])
  const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setSession({loading:false,authenticated:false,user:null});setData(null)}
  if(session.loading)return <Centered title="Fuel" text="Loading your dashboard." />
  if(!session.authenticated)return <SignIn />

  const s=data?.today.summary
  const workoutDetail=s?.exerciseMinutes!=null?`${fmt(s.exerciseMinutes)} total exercise minutes`:`${data?.today.workouts.length||0} activity summaries`
  return <main className="app-shell">
    <header className="topbar">
      <div className="brand">
        <div className="profile-shell">
          <button className="profile-button" onClick={()=>setProfileOpen(v=>!v)} aria-label="Open profile menu" aria-expanded={profileOpen}>
            {session.user?.picture?<img src={session.user.picture} alt="" referrerPolicy="no-referrer"/>:<span>{(session.user?.name||session.user?.email||'U').slice(0,1).toUpperCase()}</span>}
          </button>
          {profileOpen&&<ProfileMenu user={session.user} onSync={()=>{setProfileOpen(false);setSyncOpen(true)}} onLogout={logout}/>} 
        </div>
        <div><h1>Fuel</h1><p>{longDate(s?.date||new Date().toISOString().slice(0,10))}</p></div>
      </div>
      <div className="user"><button className="refresh-button" onClick={load} aria-label="Refresh dashboard"><RefreshCw size={17} className={loading?'spin':''}/></button></div>
    </header>
    {error&&<div className="error">{error}</div>}
    <EnergyHero summary={s} trends={data?.trends||[]} range={range} setRange={setRange}/>
    <Section title="Nutrition" detail="Daily intake compared with targets" />
    <section className="panel nutrition-panel"><GoalRing label="Calories" value={s?.caloriesConsumed} target={data?.goals.calories?.target ?? Math.max(0,(s?.totalExpenditure||2300)-350)} unit="kcal"/><GoalBar label="Protein" value={s?.protein} target={data?.goals.protein?.target||112} unit="g"/><GoalBar label="Carbohydrates" value={s?.carbs} target={data?.goals.carbs?.target||300} unit="g"/><GoalBar label="Fat" value={s?.fat} target={data?.goals.fat?.target||60} unit="g"/><GoalBar label="Fiber" value={s?.fiber} target={data?.goals.fiber?.target||30} unit="g"/></section>
    <Section title="Food consumed" detail={`${data?.today.foodEntries.length||0} entries today`}/><section className="panel"><EntryList empty="No food logged today.">{(data?.today.foodEntries||[]).map((e,i)=><FoodRow key={i} e={e}/>)}</EntryList></section>
    <Section title="Fitness" detail="Daily activity totals from Apple Health"/><ActivityRings summary={s}/>
    <section className="metric-grid fitness-metrics"><Metric icon={<Activity/>} label="Active energy" value={s?.activeEnergy} unit="kcal"/><Metric icon={<Clock3/>} label="Exercise" value={s?.exerciseMinutes} unit="min"/><Metric icon={<Route/>} label="Walking + running" value={s?.distanceMiles} unit="mi" decimals={2}/><Metric icon={<Footprints/>} label="Steps" value={s?.stepCount} unit=""/>{positive(s?.standMinutes)&&<Metric icon={<Clock3/>} label="Stand time" value={s?.standMinutes} unit="min"/>}{positive(s?.flightsClimbed)&&<Metric icon={<Activity/>} label="Flights climbed" value={s?.flightsClimbed} unit="flights"/>}{positive(s?.cyclingDistanceMiles)&&<Metric icon={<Bike/>} label="Cycling distance" value={s?.cyclingDistanceMiles} unit="mi" decimals={2}/>}</section>
    <Section title="Workouts" detail={workoutDetail}/><section className="panel"><EntryList empty="No workout activity logged today.">{(data?.today.workouts||[]).map((e,i)=><WorkoutRow key={i} e={e}/>)}</EntryList></section>
    <Section title="Steps" detail="Interactive 30-day movement trend"/><section className="panel chart-panel"><InteractiveLine data={data?.trends||[]} metric="stepCount" unit="steps" chartTitle="Daily steps" yLabel="Steps"/></section>
    <Section title="Vitals" detail="Resting cardiovascular, oxygen, and respiratory measures"/><section className="metric-grid"><Metric icon={<HeartPulse/>} label="Resting heart rate" value={s?.restingHeartRate} unit="bpm"/><Metric icon={<Activity/>} label="HRV" value={s?.hrv} unit="ms"/><Metric icon={<Activity/>} label="Respiratory rate" value={s?.respiratoryRate} unit="/min" decimals={1}/><Metric icon={<Activity/>} label="VO₂ max" value={s?.vo2Max} unit="mL/kg/min" decimals={1}/>{positive(s?.bloodOxygen)&&<Metric icon={<Activity/>} label="Blood oxygen" value={s?.bloodOxygen} unit="%" decimals={1}/>} {positive(s?.walkingHeartRateAverage)&&<Metric icon={<HeartPulse/>} label="Walking heart rate" value={s?.walkingHeartRateAverage} unit="bpm avg"/>}</section>
    <section className="panel chart-panel"><InteractiveLine data={data?.trends||[]} metric="restingHeartRate" unit="bpm" chartTitle="Resting heart rate trend" yLabel="Beats per minute"/></section>
    <Section title="Recovery" detail="Sleep and readiness context"/><section className="recovery-grid"><Metric icon={<Moon/>} label="Sleep" value={s?.sleepHours} unit="h" display={duration(s?.sleepHours)}/><section className="panel chart-panel"><InteractiveLine data={data?.trends||[]} metric="sleepHours" unit="h" decimals={1} chartTitle="Sleep duration" yLabel="Hours"/></section></section>
    <footer><Database size={15}/><span>{data?.coverage.days||0} days · {data?.coverage.workouts||0} active days · {data?.coverage.foodEntries||0} food entries · Neon Postgres</span></footer>
    {syncOpen&&<SyncSetup onClose={()=>setSyncOpen(false)}/>} 
  </main>
}

function ProfileMenu({user,onSync,onLogout}:{user:SessionUser|null;onSync:()=>void;onLogout:()=>void}){return <div className="profile-menu panel" role="menu"><div className="profile-menu-user"><strong>{user?.name||'Signed in'}</strong><span>{user?.email}</span></div><button onClick={onSync} role="menuitem"><Settings size={17}/><span>Sync setup</span></button><button className="logout-menu-button" onClick={onLogout} role="menuitem"><LogOut size={17}/><span>Log out</span></button></div>}

function SyncSetup({onClose}:{onClose:()=>void}){
  const [record,setRecord]=useState<SyncToken|null>(null)
  const [busy,setBusy]=useState(true)
  const [message,setMessage]=useState('')
  const fetchToken=useCallback(async(method:'GET'|'POST'='GET')=>{setBusy(true);setMessage('');try{const r=await fetch('/api/health/token',{method,headers:{Accept:'application/json'}});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to provide a health sync token.');setRecord(p)}catch(e){setMessage(e instanceof Error?e.message:'Unable to provide a health sync token.')}finally{setBusy(false)}},[])
  useEffect(()=>{void fetchToken()},[fetchToken])
  const copy=async()=>{if(!record?.token)return;await navigator.clipboard.writeText(record.token);setMessage('Token copied.')}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="sync-modal panel" role="dialog" aria-modal="true" aria-labelledby="sync-title"><div className="sync-modal-head"><div><h2 id="sync-title">Apple Health sync</h2><p>Neon-backed private storage</p></div><button className="icon-button" onClick={onClose} aria-label="Close sync setup"><X size={20}/></button></div><ol><li><a href={record?.shortcutUrl||'https://www.icloud.com/shortcuts/bfdc6b641b3f4172a7b842fc60dc1dd3'} target="_blank" rel="noreferrer">Install the Fuel Health Shortcut</a>.</li><li>Replace only the bearer token in the Shortcut with the token below.</li><li>Leave the endpoint and the word <strong>Bearer</strong> unchanged.</li></ol><label>Your bearer token</label><div className="token-box">{busy?'Loading token…':record?.token||'Token unavailable'}</div><button className="primary-sync-button" onClick={copy} disabled={!record?.token||busy}><Copy size={17}/>Copy token</button><div className="sync-actions"><a className="shortcut-button" href={record?.shortcutUrl||'https://www.icloud.com/shortcuts/bfdc6b641b3f4172a7b842fc60dc1dd3'} target="_blank" rel="noreferrer">Get Shortcut</a><button className="resync-button" onClick={()=>void fetchToken('POST')} disabled={busy}><RefreshCw size={16}/>Re-sync token</button></div>{message&&<p className="sync-message">{message}</p>}<p className="sync-note">Re-syncing immediately revokes the previous token. Imports update one record per date and do not create duplicate daily entries.</p></section></div>
}

function ActivityRings({summary}:{summary:Summary|undefined}){const rings=[{label:'Move',value:summary?.activeEnergy||0,target:1000,unit:'CAL',radius:96,width:26,className:'move-ring'},{label:'Exercise',value:summary?.exerciseMinutes||0,target:80,unit:'MIN',radius:67,width:24,className:'exercise-ring'},{label:'Stand',value:summary?.standMinutes||0,target:120,unit:'MIN',radius:40,width:22,className:'stand-ring'}];const {ref,visible}=useInView<HTMLDivElement>();return <section ref={ref} className={`activity-rings panel ${visible?'is-visible':''}`}><div className="rings-graphic" role="img" aria-label={`Move ${fmt(summary?.activeEnergy)} of 1000 calories, exercise ${fmt(summary?.exerciseMinutes)} of 80 minutes, stand ${fmt(summary?.standMinutes)} of 120 minutes`}><svg viewBox="0 0 240 240" aria-hidden="true">{rings.map(r=>{const c=2*Math.PI*r.radius,pct=Math.min(1,Math.max(0,r.value/r.target));return <g key={r.label} className={r.className}><circle className="fitness-track" cx="120" cy="120" r={r.radius} strokeWidth={r.width}/><circle className="fitness-progress" cx="120" cy="120" r={r.radius} strokeWidth={r.width} strokeDasharray={c} strokeDashoffset={c*(1-pct)}/></g>})}</svg></div><div className="rings-copy">{rings.map(r=><div className={`ring-stat ${r.className}`} key={r.label}><span>{r.label}</span><strong>{fmt(r.value)}/{fmt(r.target)}<small>{r.unit}</small></strong></div>)}</div></section>}

function EnergyHero({summary,trends,range,setRange}:{summary:Summary|undefined;trends:TrendPoint[];range:RangeKey;setRange:(r:RangeKey)=>void}){const days=range==='day'?1:range==='week'?7:30,visible=trends.slice(-days),consumed=visible.reduce((a,p)=>a+(p.caloriesConsumed||0),0),expended=visible.reduce((a,p)=>a+(p.totalExpenditure||0),0),balance=consumed&&expended?consumed-expended:null;return <section className="hero panel"><div className="hero-head"><div><span className="eyebrow">ENERGY BALANCE</span><h2>{balance==null?'Incomplete data':balance>0?`${fmt(balance)} kcal surplus`:`${fmt(Math.abs(balance))} kcal deficit`}</h2><p>{range==='day'?'Today':range==='week'?'Last 7 days':'Last 30 days'} · intake versus total expenditure</p></div><div className="tabs">{(['day','week','month'] as RangeKey[]).map(r=><button className={range===r?'active':''} onClick={()=>setRange(r)} key={r}>{r==='day'?'Day':r==='week'?'Week':'Month'}</button>)}</div></div><EnergyInteractiveChart data={visible}/><div className="hero-stats"><Stat label="Consumed" value={consumed||summary?.caloriesConsumed}/><Stat label="Resting" value={range==='day'?summary?.restingEnergy:visible.reduce((a,p)=>a+(p.restingEnergy||0),0)}/><Stat label="Active" value={range==='day'?summary?.activeEnergy:visible.reduce((a,p)=>a+(p.activeEnergy||0),0)}/><Stat label="Expended" value={expended||summary?.totalExpenditure}/></div></section>}

function EnergyInteractiveChart({data}:{data:TrendPoint[]}){const [active,setActive]=useState<number|null>(null),max=Math.max(1,...data.flatMap(p=>[p.caloriesConsumed||0,p.totalExpenditure||0]));if(!data.length)return <div className="empty">No energy data</div>;const p=active==null?null:data[active];return <div className="energy-viz animated-chart is-visible" onMouseLeave={()=>setActive(null)}><div className="chart-header-row"><div><strong className="chart-title">Daily energy intake and expenditure</strong><span className="chart-axis-note">Horizontal axis: date · Vertical axis: kilocalories</span></div><ChartLegend items={[["legend-consumed","Calories consumed"],["legend-expended","Total calories expended"]]}/></div><div className="bars" aria-label="Energy chart by date">{data.map((d,i)=><button key={d.date} className={`bar-day ${i===active?'selected':''}`} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onBlur={()=>setActive(null)} onClick={()=>setActive(i)}><span className="bar consumed" style={{'--bar-height':`${Math.max(3,(d.caloriesConsumed||0)/max*100)}%`} as CSSProperties}/><span className="bar burned" style={{'--bar-height':`${Math.max(3,(d.totalExpenditure||0)/max*100)}%`} as CSSProperties}/>{i===active&&p&&<span className="point-label energy-point-label"><strong>{dateFmt(p.date)}</strong><span>{fmt(p.caloriesConsumed)} in</span><span>{fmt(p.totalExpenditure)} out</span></span>}<small>{dateFmt(d.date)}</small></button>)}</div><div className="x-axis-label">Date</div></div>}

function InteractiveLine({data,metric,unit,decimals=0,chartTitle,yLabel}:{data:TrendPoint[];metric:keyof TrendPoint;unit:string;decimals?:number;chartTitle:string;yLabel:string}){const points=data.map((p,i)=>({date:p.date,value:typeof p[metric]==='number'?p[metric] as number:null,i})).filter((p):p is {date:string;value:number;i:number}=>p.value!=null),[active,setActive]=useState<number|null>(null);if(points.length<2)return <div className="empty">Insufficient data</div>;const max=Math.max(...points.map(p=>p.value)),min=Math.min(...points.map(p=>p.value)),w=760,h=220,padX=42,padY=30,range=max-min||1,xy=points.map((p,i)=>({...p,x:padX+i/(points.length-1)*(w-padX*2),y:padY+(max-p.value)/range*(h-padY*2)})),a=active==null?null:xy[active],first=xy[0],last=xy.at(-1)!,labelLeft=a?`${Math.min(86,Math.max(12,(a.x/w)*100))}%`:'50%',labelTop=a?`${Math.min(80,Math.max(8,(a.y/h)*100))}%`:'50%';return <div className="interactive-line animated-chart is-visible" onMouseLeave={()=>setActive(null)}><div className="chart-header-row"><div><strong className="chart-title">{chartTitle}</strong><span className="chart-axis-note">Horizontal axis: date · Vertical axis: {yLabel}</span></div><ChartLegend items={[["legend-line",chartTitle]]}/></div><div className="chart-stage"><span className="y-axis-label">{yLabel}</span><svg viewBox={`0 0 ${w} ${h}`} role="img" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect(),idx=Math.round(((e.clientX-r.left)/r.width)*(points.length-1));setActive(Math.max(0,Math.min(points.length-1,idx)))}}><defs><linearGradient id={`fill-${String(metric)}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopOpacity=".18"/><stop offset="1" stopOpacity="0"/></linearGradient></defs><line className="gridline" x1={padX} x2={w-padX} y1={padY} y2={padY}/><line className="gridline" x1={padX} x2={w-padX} y1={h-padY} y2={h-padY}/><path className="area" d={`M ${xy[0].x} ${h-padY} L ${xy.map(p=>`${p.x} ${p.y}`).join(' L ')} L ${xy.at(-1)!.x} ${h-padY} Z`} fill={`url(#fill-${String(metric)})`}/><polyline className="trend-line" points={xy.map(p=>`${p.x},${p.y}`).join(' ')} fill="none"/>{a&&<line className="cursor" x1={a.x} x2={a.x} y1={padY} y2={h-padY}/>} {xy.map((p,i)=><circle key={p.date} cx={p.x} cy={p.y} r={i===active?6:3} onClick={()=>setActive(i)} onFocus={()=>setActive(i)} tabIndex={0}/>)}</svg>{a&&<div className="point-label line-point-label" style={{left:labelLeft,top:labelTop}}><strong>{dateFmt(a.date)}</strong><span>{fmt(a.value,decimals)} {unit}</span></div>}<span className="y-max-label">{fmt(max,decimals)} {unit}</span><span className="y-min-label">{fmt(min,decimals)} {unit}</span></div><div className="line-axis-footer"><span>{dateFmt(first.date)}</span><strong>Date</strong><span>{dateFmt(last.date)}</span></div></div>}

function ChartLegend({items}:{items:Array<[string,string]>}){return <div className="chart-legend" aria-label="Chart legend">{items.map(([className,label])=><span key={label}><i className={className}/>{label}</span>)}</div>}
function GoalRing({label,value,target,unit}:{label:string;value:N|undefined;target:number;unit:string}){const pct=Math.min(100,Math.max(0,((value||0)/target)*100)),{ref,visible}=useInView<HTMLDivElement>();return <div ref={ref} className={`goal-ring animated-metric ${visible?'is-visible':''}`}><div className="ring" style={{'--pct':`${pct*3.6}deg`} as CSSProperties}><div><strong>{fmt(value)}</strong><span>of {fmt(target)} {unit}</span></div></div><h3>{label}</h3></div>}
function GoalBar({label,value,target,unit}:{label:string;value:N|undefined;target:number;unit:string}){const pct=Math.min(120,Math.max(0,((value||0)/target)*100)),{ref,visible}=useInView<HTMLDivElement>();return <div ref={ref} className={`goal-bar animated-metric ${visible?'is-visible':''}`}><div><strong>{label}</strong><span>{fmt(value)} / {fmt(target)} {unit}</span></div><div className="track"><i style={{'--goal-width':`${Math.min(100,pct)}%`} as CSSProperties}/></div></div>}
function Metric({icon,label,value,unit,decimals=0,display}:{icon:ReactNode;label:string;value:N|undefined;unit:string;decimals?:number;display?:string}){return <section className="metric-card panel"><span>{icon}</span><div><p>{label}</p><strong>{display||fmt(value,decimals)}</strong>{value!=null&&!display&&<small>{unit}</small>}</div></section>}
function Stat({label,value}:{label:string;value:N|undefined}){return <div><span>{label}</span><strong>{fmt(value)} kcal</strong></div>}
function Section({title,detail}:{title:string;detail:string}){return <div className="section-title"><h2>{title}</h2><p>{detail}</p></div>}
function EntryList({children,empty}:{children:ReactNode;empty:string}){const a=Array.isArray(children)?children:[children];return a.length?<div className="entry-list">{children}</div>:<div className="empty">{empty}</div>}
function FoodRow({e}:{e:FoodEntry}){return <article className="entry"><div><strong>{e.food||e.meal}</strong><span>{[e.time,e.meal,e.portion].filter(Boolean).join(' · ')}</span></div><div><strong>{fmt(e.calories)} kcal</strong><span>{fmt(e.protein,1)}g protein · {fmt(e.carbs,1)}g carbs · {fmt(e.fat,1)}g fat</span></div></article>}
function WorkoutRow({e}:{e:WorkoutEntry}){const facts=[e.swimmingDistanceYards!=null?`${fmt(e.swimmingDistanceYards)} yd`:e.distanceMiles!=null?`${fmt(e.distanceMiles,2)} mi`:'',e.strokeCount!=null?`${fmt(e.strokeCount)} strokes`:'',e.stepCount!=null?`${fmt(e.stepCount)} steps`:''].filter(Boolean);return <article className="entry"><div><strong>{e.activity||'Activity'}</strong><span>{facts.join(' · ')||e.dataQuality}</span></div><div><span>{e.dataQuality}</span></div></article>}
function Centered({title,text}:{title:string;text:string}){return <main className="center"><RefreshCw className="spin"/><h1>{title}</h1><p>{text}</p></main>}
function SignIn(){return <main className="center"><div className="signin"><h1>Fuel</h1><p>Your private nutrition, activity, and recovery dashboard.</p><button onClick={()=>location.assign('/api/auth/google/start')}><ShieldCheck size={18}/>Sign in with Google</button></div></main>}
