import { useEffect } from 'react'
import type { ReactNode } from 'react'
import { ArrowLeft, BookOpen, ChevronRight, Target, Timer } from 'lucide-react'
import { workoutPlans } from './workouts'
import type { LiftPlan } from './workouts'
import './Lifting.css'

// Lazy-loaded from App.tsx: this page owns the whole workout-plan dataset (~23 KB)
// plus its stylesheet, which the dashboard never needs on first paint.
export default function LiftingPage({selected,onSelect,nav}:{selected:LiftPlan|null;onSelect:(p:LiftPlan|null)=>void;nav:ReactNode}){
  useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'})},[selected])
  if(selected)return <main className="app-shell lifting-page">{nav}<div className="lifting-subhead"><button className="back-button" onClick={()=>onSelect(null)} aria-label="Back to lifting plans"><ArrowLeft size={18}/></button><div><h1>Lifting</h1><p>View-only plan. Apple Health remains the activity log.</p></div></div><article className="lift-detail"><section className="panel lift-detail-hero"><span className={`level-pill level-${selected.level}`}>{selected.level}</span><h1>{selected.title}</h1><p>{selected.summary}</p><div className="lift-detail-meta"><span><Timer size={16}/>{selected.duration}</span><span><Target size={16}/>{selected.focus}</span></div><div className="lift-card-tags">{selected.tags.map(t=><span className="lift-tag" key={t}>{t}</span>)}</div></section><section className="panel lift-steps">{selected.steps.map((step,i)=><div className="lift-step" key={`${step.exercise}-${i}`}><div className="lift-phase">{step.phase}</div><div><h3>{step.exercise}</h3><p>{step.prescription}</p>{step.rest&&<p className="rest">Rest: {step.rest}</p>}{step.cues&&<p className="cues">{step.cues}</p>}</div></div>)}</section><section className="panel lifting-note">Choose loads that preserve the listed repetitions in reserve (RIR). Technical failure means the next repetition would require altered range, posture, or assistance. Do not force painful ranges, and use a spotter or safety arms for heavy presses and squats.</section></article></main>
  return <main className="app-shell lifting-page">{nav}<section className="panel lifting-intro"><h2>Choose a 30-45 minute session.</h2><p>These plans prioritize high-quality compound work, controlled weekly fatigue, and time-efficient supersets. Most working sets stop one to three repetitions before technical failure. Drop sets and cluster sets are used selectively rather than as defaults, and the recovery sessions stay deliberately easy.</p><div className="lifting-principles"><span>Dynamic warm-up first</span><span>1-3 reps in reserve</span><span>Compound lifts prioritized</span><span>Static stretching last</span><span>No logging from this page</span></div></section><div className="lift-grid">{workoutPlans.map(plan=><button className="lift-card" key={plan.id} onClick={()=>onSelect(plan)}><div className="lift-card-head"><h3>{plan.title}</h3><ChevronRight className="chevron" size={18}/></div><p className="lift-focus">{plan.focus}</p><p className="lift-summary">{plan.summary}</p><div className="lift-card-meta"><span><Timer size={14}/>{plan.duration}</span><span className={`level-pill level-${plan.level}`}>{plan.level}</span></div><div className="lift-card-tags">{plan.tags.map(t=><span className="lift-tag" key={t}>{t}</span>)}</div></button>)}</div><section className="panel lifting-research"><h3><BookOpen size={17}/> Programming basis</h3><p>The library uses progressive resistance training principles, adequate rest for strength work, moderate proximity to failure, full-range compound movements, and non-competing supersets when time is limited. Dynamic movements prepare the session, while short static holds are reserved for the end. Because running and swimming already create substantial endurance load, lower-body volume and failure work are constrained to protect recovery.</p></section></main>
}
